spring.application.name=cineapi

# Configurações de conexão com o Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/cineapi
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Exibir as queries SQL no console (ajuda muito a estudar e debugar!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true